name: Build Geode Mod

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build the Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          # This tells the action to build the mod in the root directory
          path: '.'
          # This ensures the action uses the latest available tools
          sdk: nightly
          
